baseURL = "http://jugf.de/"
languageCode = "en-us"
title = "Main"
theme = "ananke"
copyright = "Java User Group Frankfurt"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "img/favicon.ico"
  site_logo = ""
  description = "JUG Frankfurt | JUGF | Homepage"
  twitter = "https://twitter.com/jugffm"
  rss = ""
  background_color_class = "bg-black"
  featured_image = "img/jugf_convertio.svg"
  recent_posts_number = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true